Dragon-Deny-Damage-Message: "You can't damage the Ender Dragon before the event."
Crystal-Deny-Damage-Message: "You can't damage the Ender Crystals before the event."
Dragon-Fight-Starting-In-Message: "The Ender Dragon Fight will begin in 5 minutes get ready."
Dragon-Fight-Started-Message: "The Ender Dragon Fight has started."
Dragon-Death-Message: "The Dragon has been slain."
# 1000 ticks = 1 minute
Dragon-Fight-Start-Delay: 6000